/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jia13_youyue_crypto_AES */

#ifndef _Included_com_jia13_youyue_crypto_AES
#define _Included_com_jia13_youyue_crypto_AES
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jia13_youyue_crypto_AES
 * Method:    Encrypto
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_jia13_youyue_crypto_AES_Encrypto
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_jia13_youyue_crypto_AES
 * Method:    Decrypto
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_jia13_youyue_crypto_AES_Decrypto
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
