/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jia13_youyue_crypto_Base64 */

#ifndef _Included_com_jia13_youyue_crypto_Base64
#define _Included_com_jia13_youyue_crypto_Base64
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jia13_youyue_crypto_Base64
 * Method:    encode
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_jia13_youyue_crypto_Base64_encode
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_jia13_youyue_crypto_Base64
 * Method:    decode
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_jia13_youyue_crypto_Base64_decode
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
